def on_forever():
    basic.show_icon(IconNames.HAPPY)
    basic.show_string("Welcome")
    basic.show_icon(IconNames.HAPPY)
    basic.show_string("Enya")
    basic.show_icon(IconNames.HAPPY)
    basic.show_string("Anna")
    basic.show_icon(IconNames.HAPPY)
    basic.show_string("Jing")
    basic.show_icon(IconNames.HAPPY)
    basic.show_string("Chao-Ge")
    basic.show_icon(IconNames.HAPPY)
    basic.show_string("Dong")
basic.forever(on_forever)
