basic.forever(function () {
    basic.showIcon(IconNames.Happy)
    basic.showString("Welcome")
    basic.showIcon(IconNames.Happy)
    basic.showString("Enya")
    basic.showIcon(IconNames.Happy)
    basic.showString("Anna")
    basic.showIcon(IconNames.Happy)
    basic.showString("Jing")
    basic.showIcon(IconNames.Happy)
    basic.showString("Chao-Ge")
    basic.showIcon(IconNames.Happy)
    basic.showString("Dong")
})
